name: rentaroof
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  motion_tab_bar_v2: ^0.3.0
  circular_bottom_navigation: ^2.2.0
  font_awesome_flutter: ^10.2.1
  shared_preferences: ^2.0.15
  carousel_slider: ^5.0.0
  cached_network_image: ^3.2.2
  shimmer: ^3.0.0
  flutter_svg: ^2.0.17


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/Images/
    - assets/Images/drawer/
    - assets/Icons/
    - assets/Icons/detail page/
    - assets/Icons/Manage visits/
    - assets/Icons/menu/
    - assets/Icons/sidemenu/